### PR TITLE
Add option & ".norminetteignore" file to ignore files

### PR DESCRIPTION
**Pull request by courtier**

### CODE REVIEW

**Comment by courtier** [comment]
Thinking about this again, the .norminetteignore file could be abused if the reviewer fails to see the the file and does not realize some files are being ignored. I will add an option to enable the usage of the file.

**Comment by GlaceCoding** [comment]
I think you should not add the `-g` alias because it is not explicit. This one could be abused by some people saying `-g` is for global searching. 😅

**Comment by courtier** [comment]
You're right.

**Comment by N0ich** [comment]
Hello and sorry, but I can't merge this as the basic usage of the norminette should not require any ignored files. Besides, it becomes easy to "hide" files during an evaluation so all in all, it's probably safer without it.

**Pull request closed without merging**
